# Generated by Django 3.0 on 2020-05-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audittype', models.CharField(max_length=25, null=True)),
                ('cls_refno', models.CharField(max_length=8, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('auditor_comments', models.TextField()),
                ('auditor_status', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=25, null=True)),
                ('auditee_comments', models.TextField(null=True)),
                ('auditee_status', models.CharField(max_length=15, null=True)),
                ('verified_comments', models.TextField(null=True)),
                ('verified_status', models.CharField(max_length=10)),
                ('mr_comments', models.TextField(null=True)),
                ('mr_status', models.CharField(max_length=10, null=True)),
                ('create_by', models.CharField(max_length=50)),
                ('create_on', models.DateTimeField(auto_now=True)),
                ('create_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_comments',
            },
        ),
        migrations.CreateModel(
            name='Audittype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audittype', models.CharField(max_length=25)),
                ('auditcode', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'audittype',
            },
        ),
        migrations.CreateModel(
            name='ClientName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clients_name',
            },
        ),
        migrations.CreateModel(
            name='EmployeDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'master_department',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=3)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_reporting_to', models.CharField(max_length=50)),
                ('emp_approved_by', models.CharField(max_length=50)),
                ('emp_status', models.CharField(max_length=20)),
                ('emp_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_department', to='QMS.EmployeDepartment')),
            ],
            options={
                'db_table': 'employee_details',
            },
        ),
        migrations.CreateModel(
            name='EmployePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_posn', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'master_position',
            },
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_user', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'end_users',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'job_type',
            },
        ),
        migrations.CreateModel(
            name='WorkManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_ref_no', models.CharField(max_length=10)),
                ('activity_title', models.CharField(max_length=100)),
                ('ISO_certification_year', models.IntegerField()),
                ('type_of_projectortender', models.CharField(max_length=10)),
                ('explain_of_activity', models.TextField()),
                ('audit_typ', models.ManyToManyField(blank=True, related_name='audit_typ', to='QMS.Audittype')),
            ],
            options={
                'db_table': 'work_manual',
            },
        ),
        migrations.CreateModel(
            name='ManualCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.TextField()),
                ('workmanual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workmanual', to='QMS.WorkManual')),
            ],
            options={
                'db_table': 'work_manual_checklist',
            },
        ),
        migrations.CreateModel(
            name='ListAuditors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditors', to='QMS.EmployeeDetails')),
            ],
            options={
                'db_table': 'list_auditors',
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=25)),
                ('job_startdate', models.DateField()),
                ('job_enddate', models.DateField()),
                ('job_Description', models.TextField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='QMS.ClientName')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_user', to='QMS.EndUser')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_type', to='QMS.JobType')),
            ],
            options={
                'db_table': 'job_details',
            },
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='emp_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_position', to='QMS.EmployePosition'),
        ),
        migrations.CreateModel(
            name='Auditschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_job_code', models.CharField(max_length=15)),
                ('schedule_sub_job_code', models.CharField(blank=True, max_length=15, null=True)),
                ('schedule_job_audit_no', models.CharField(blank=True, max_length=15, null=True)),
                ('schedule_audit_no', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_audit_code', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_audit_date', models.DateField()),
                ('schedule_audit_time', models.TimeField()),
                ('schedule_department_status', models.IntegerField(default=0)),
                ('schedule_department_username', models.CharField(blank=True, max_length=15, null=True)),
                ('schedule_department_date', models.DateField(blank=True, null=True)),
                ('schedule_audit_mr_status', models.IntegerField(default=0)),
                ('schedule_description', models.CharField(blank=True, max_length=15, null=True)),
                ('schedule_audit_status', models.IntegerField(default=0)),
                ('schedule_file_path', models.URLField(blank=True, max_length=500, null=True)),
                ('schedule_iso_year', models.IntegerField()),
                ('create_by', models.CharField(max_length=50)),
                ('create_on', models.DateTimeField(auto_now=True)),
                ('create_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('schedule_auditee_list', models.ManyToManyField(blank=True, related_name='auditee_list', to='QMS.EmployeeDetails')),
                ('schedule_auditor_list', models.ManyToManyField(blank=True, related_name='auditor_list', to='QMS.ListAuditors')),
                ('schedule_auditype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_type', to='QMS.Audittype')),
                ('schedule_final_auditor_list', models.ManyToManyField(blank=True, related_name='final_auditor_list', to='QMS.ListAuditors')),
                ('schedule_team_member_list', models.ManyToManyField(blank=True, related_name='team_member_list', to='QMS.EmployeeDetails')),
            ],
            options={
                'db_table': 'audit_schedule',
            },
        ),
        migrations.CreateModel(
            name='Auditorlist_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorlisttwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorlisttwo', to='QMS.EmployeeDetails')),
            ],
            options={
                'db_table': 'auditorlist_two',
            },
        ),
    ]
