# Generated by Django 3.0 on 2020-05-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit_comments',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='audit_comments',
            name='create_ip',
        ),
        migrations.RemoveField(
            model_name='audit_comments',
            name='create_on',
        ),
        migrations.RemoveField(
            model_name='audit_comments',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='audit_comments',
            name='modified_ip',
        ),
        migrations.RemoveField(
            model_name='audit_comments',
            name='modified_on',
        ),
    ]
