# Generated by Django 3.0 on 2020-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0002_auto_20200519_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_comments',
            name='create_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audit_comments',
            name='create_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit_comments',
            name='create_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audit_comments',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audit_comments',
            name='modified_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit_comments',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='auditee_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='auditee_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='auditor_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='mr_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='mr_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='verified_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='verified_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
