# Generated by Django 3.0 on 2020-05-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0003_auto_20200519_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_comments',
            name='auditor_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='audittype',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='cls_refno',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='department',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
