# Generated by Django 3.0 on 2020-05-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0005_auto_20200519_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_comments',
            name='auditor_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='verified_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
