# Generated by Django 3.0 on 2020-05-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0006_auto_20200519_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_comments',
            name='auditee_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='auditee_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='auditor_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='auditor_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='audittype',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='cls_refno',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='create_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='department',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='modified_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='mr_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='mr_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='verified_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='verified_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
