# Generated by Django 3.0 on 2020-05-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0007_auto_20200520_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_comments',
            name='mr_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='mr_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
