# Generated by Django 3.0 on 2020-05-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0008_auto_20200530_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_comments',
            name='mr_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_comments',
            name='mr_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
