# Generated by Django 3.0 on 2020-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0010_auto_20200603_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpond',
            name='auditschedule_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
