# Generated by Django 3.0 on 2020-06-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0011_auto_20200603_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_comments',
            name='auditschedule_id',
            field=models.IntegerField(null=True),
        ),
    ]
