# Generated by Django 3.0 on 2020-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0012_audit_comments_auditschedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_comments',
            name='workmanual_id',
            field=models.IntegerField(null=True),
        ),
    ]
