# Generated by Django 3.0 on 2020-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0013_audit_comments_workmanual_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditschedule',
            name='create_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='create_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='schedule_audit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='schedule_audit_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='schedule_iso_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='auditschedule',
            name='schedule_job_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
