# Generated by Django 3.0 on 2020-06-16 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0016_auto_20200615_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmanual',
            name='type_of_projectortender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, default=list, null=True, size=None),
        ),
    ]
