# Generated by Django 3.0 on 2020-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS', '0017_auto_20200616_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditscheduleConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditschedule_id', models.CharField(max_length=4, null=True)),
                ('auditee_name', models.CharField(max_length=50, null=True)),
                ('auditee_department', models.CharField(max_length=50, null=True)),
                ('approved_by', models.CharField(max_length=50, null=True)),
                ('approved_status', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'auditschedule_confirm',
            },
        ),
    ]
